name: Test FTP Connection

on:
  workflow_dispatch:

jobs:
  test-ftp-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List Remote Directory
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.STG_SFTP_HOST }}
        username: ${{ secrets.STG_SFTP_USER }}
        password: ${{ secrets.STG_SFTP_PASS }}
        local-dir: .
        server-dir: /site/wwwroot
        dry-run: true  # Perform a dry run to list files without making changes
        protocol: ftps  # Ensure FTPS is being used
        log-level: verbose  # Enable verbose logging
