name: Deploy to Azure Staging Server via FTPS

on:
  push:
    branches:
      - CS-Dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via FTPS to Azure Staging Server
        uses: actions/checkout@v2

      # Example: Build step (if applicable)
      # - name: Build
      #   run: |
      #     npm install
      #     npm run build

      - name: Deploy via FTPS to Azure Staging Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.STG_SFTP_HOST }}
          username: ${{ secrets.STG_SFTP_USER }}
          password: ${{ secrets.STG_SFTP_PASS }}
          server-dir: /home/site/wwwroot/
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/public/**
            test.php
            .gitignore
          timeout: 60000   
