name: Deploy to Azure Staging Server via FTPS

on:
  push:
    branches:
      - CS-Dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via FTPS to Azure Staging Server
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.STG_SFTP_HOST }}
          ftp-username: ${{ secrets.STG_SFTP_USER }}
          ftp-password: ${{ secrets.STG_SFTP_PASS }}
          local-dir: .
          git-ftp-args: "--remote-root /site/wwwroot/ --ftp-ssl --exclude .git* --exclude .git*/** --exclude node_modules/** --exclude vendor/** --exclude public/** --exclude test.php --exclude .gitignore"
